name: Version

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Bumb with semver version'
        required: true
        default: patch

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure git information
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'sonvo95@outlook.com'

      - name: Bump version
        run: npm version ${{ github.event.inputs.newversion }} -m "$(git log --oneline --decorate=no $(git describe --tags --abbrev=0)..HEAD)"

      - name: Push updates
        run: git push --follow-tags
